`timescale 1ns/1ps

module tb_bucket_build_4L;

    logic [255:0] P0_X, P0_Y;
    logic [255:0] P1_X, P1_Y;
    logic [255:0] P2_X, P2_Y;
    logic [255:0] P3_X, P3_Y;

    logic [1:0] P0_bid;
    logic [1:0] P1_bid;
    logic [1:0] P2_bid;
    logic [1:0] P3_bid;

    logic [255:0] B1_X, B1_Y, B1_Z;
    logic [255:0] B2_X, B2_Y, B2_Z;
    logic [255:0] B3_X, B3_Y, B3_Z;

    bucket_build_4L dut (
        .i_P0_X   (P0_X),
        .i_P0_Y   (P0_Y),
        .i_P0_bid (P0_bid),

        .i_P1_X   (P1_X),
        .i_P1_Y   (P1_Y),
        .i_P1_bid (P1_bid),

        .i_P2_X   (P2_X),
        .i_P2_Y   (P2_Y),
        .i_P2_bid (P2_bid),

        .i_P3_X   (P3_X),
        .i_P3_Y   (P3_Y),
        .i_P3_bid (P3_bid),

        .o_B1_X   (B1_X),
        .o_B1_Y   (B1_Y),
        .o_B1_Z   (B1_Z),

        .o_B2_X   (B2_X),
        .o_B2_Y   (B2_Y),
        .o_B2_Z   (B2_Z),

        .o_B3_X   (B3_X),
        .o_B3_Y   (B3_Y),
        .o_B3_Z   (B3_Z)
    );


    task automatic check_no_x;
        begin
            if ((^B1_X === 1'bx) || (^B1_Y === 1'bx) || (^B1_Z === 1'bx) ||
                (^B2_X === 1'bx) || (^B2_Y === 1'bx) || (^B2_Z === 1'bx) ||
                (^B3_X === 1'bx) || (^B3_Y === 1'bx) || (^B3_Z === 1'bx)) begin

                $display("[FAIL] Output contains X");

                $display("B1_X = %h", B1_X);
                $display("B1_Y = %h", B1_Y);
                $display("B1_Z = %h", B1_Z);

                $display("B2_X = %h", B2_X);
                $display("B2_Y = %h", B2_Y);
                $display("B2_Z = %h", B2_Z);

                $display("B3_X = %h", B3_X);
                $display("B3_Y = %h", B3_Y);
                $display("B3_Z = %h", B3_Z);

                $fatal;
            end else begin
                $display("[PASS] No X values");
            end
        end
    endtask


    task automatic check_bucket;
        input string name;

        input logic [255:0] got_x;
        input logic [255:0] got_y;
        input logic [255:0] got_z;

        input logic [255:0] exp_x;
        input logic [255:0] exp_y;
        input logic [255:0] exp_z;

        begin
            if ((got_x !== exp_x) || (got_y !== exp_y) || (got_z !== exp_z)) begin
                $display("[FAIL] %s mismatch", name);

                $display("%s_X     = %h", name, got_x);
                $display("EXP_%s_X = %h", name, exp_x);

                $display("%s_Y     = %h", name, got_y);
                $display("EXP_%s_Y = %h", name, exp_y);

                $display("%s_Z     = %h", name, got_z);
                $display("EXP_%s_Z = %h", name, exp_z);

                $fatal;
            end else begin
                $display("[PASS] %s matches expected Python reference", name);
            end
        end
    endtask


    initial begin
        $display("========================================");
        $display("=== tb_bucket_build_4L start ===");
        $display("========================================");

        // ------------------------------------------------------------
        // Test:
        //
        // P0 = G   -> bucket 1
        // P1 = 2G  -> bucket 2
        // P2 = 3G  -> bucket 3
        // P3 = G   -> bucket 1
        //
        // Expected:
        // bucket1 = G + G = 2G
        // bucket2 = 2G
        // bucket3 = 3G
        //
        // Values generated by:
        // tests/python/gen_expected_bucket_build4.py
        // ------------------------------------------------------------

        $display("");
        $display("[TEST 1] bucket build: P0->B1, P1->B2, P2->B3, P3->B1");

        // P0 = G affine Montgomery
        P0_X   = 256'h9981e643e9089f48979f48c033fd129c231e295329bc66dbd7362e5a487e2097;
        P0_Y   = 256'hcf3f851fd4a582d670b6b59aac19c1368dfc5d5d1f1dc64db15ea6d2d3dbabe2;
        P0_bid = 2'd1;

        // P1 = 2G affine Montgomery
        P1_X   = 256'hf918623ccba0ee23ce0b62e1e014040471354afc88b285a04e0640c981048d2c;
        P1_Y   = 256'h3c7f7712157b93134b3a0f64bda2cc6584fd25167dc75ce17d12d622ffaccfbf;
        P1_bid = 2'd2;

        // P2 = 3G affine Montgomery
        P2_X   = 256'h9497730fcdf4c0ad5940d07385985972066ceafb22eb7bc42379d4bbd5fea781;
        P2_Y   = 256'h3ec28dcd9215ec76cc6048bd84885650ac4964cdc5a1f91faf18b0b0613f55a9;
        P2_bid = 2'd3;

        // P3 = G affine Montgomery
        P3_X   = 256'h9981e643e9089f48979f48c033fd129c231e295329bc66dbd7362e5a487e2097;
        P3_Y   = 256'hcf3f851fd4a582d670b6b59aac19c1368dfc5d5d1f1dc64db15ea6d2d3dbabe2;
        P3_bid = 2'd1;

        #10;

        check_no_x();

        // Expected bucket1 = 2G Jacobian Montgomery
        check_bucket(
            "B1",
            B1_X, B1_Y, B1_Z,
            256'h7c75dd9524177d593c03889b8dcd9b1cb05fb7d2a3da7fe8ba9f29b104e7db13,
            256'h55debb381f4ad034cc27cb48a46449aaa87d43fdb563384b1cd20838e6fddc9f,
            256'h9e7f0a3fa94b05ace16d6b355833826d1bf8baba3e3b8c9b62bd4da6a7b75b95
        );

        // Expected bucket2 = 2G affine as Jacobian, Z=ONE_M
        check_bucket(
            "B2",
            B2_X, B2_Y, B2_Z,
            256'hf918623ccba0ee23ce0b62e1e014040471354afc88b285a04e0640c981048d2c,
            256'h3c7f7712157b93134b3a0f64bda2cc6584fd25167dc75ce17d12d622ffaccfbf,
            256'h00000000000000000000000000000000000000000000000000000001000003d1
        );

        // Expected bucket3 = 3G affine as Jacobian, Z=ONE_M
        check_bucket(
            "B3",
            B3_X, B3_Y, B3_Z,
            256'h9497730fcdf4c0ad5940d07385985972066ceafb22eb7bc42379d4bbd5fea781,
            256'h3ec28dcd9215ec76cc6048bd84885650ac4964cdc5a1f91faf18b0b0613f55a9,
            256'h00000000000000000000000000000000000000000000000000000001000003d1
        );

        $display("");
        $display("========================================");
        $display("=== tb_bucket_build_4L PASSED ===");
        $display("========================================");

        $finish;
    end

endmodule