`timescale 1ns/1ps

module tb_pippenger_window_4L;

    logic [255:0] P0_X, P0_Y;
    logic [255:0] P1_X, P1_Y;
    logic [255:0] P2_X, P2_Y;
    logic [255:0] P3_X, P3_Y;

    logic [1:0] P0_bid;
    logic [1:0] P1_bid;
    logic [1:0] P2_bid;
    logic [1:0] P3_bid;

    logic [255:0] OUT_X;
    logic [255:0] OUT_Y;
    logic [255:0] OUT_Z;

    pippenger_window_4L dut (
        .i_P0_X   (P0_X),
        .i_P0_Y   (P0_Y),
        .i_P0_bid (P0_bid),

        .i_P1_X   (P1_X),
        .i_P1_Y   (P1_Y),
        .i_P1_bid (P1_bid),

        .i_P2_X   (P2_X),
        .i_P2_Y   (P2_Y),
        .i_P2_bid (P2_bid),

        .i_P3_X   (P3_X),
        .i_P3_Y   (P3_Y),
        .i_P3_bid (P3_bid),

        .o_X      (OUT_X),
        .o_Y      (OUT_Y),
        .o_Z      (OUT_Z)
    );


    task automatic check_no_x;
        begin
            if ((^OUT_X === 1'bx) || (^OUT_Y === 1'bx) || (^OUT_Z === 1'bx)) begin
                $display("[FAIL] Output contains X");
                $display("OUT_X = %h", OUT_X);
                $display("OUT_Y = %h", OUT_Y);
                $display("OUT_Z = %h", OUT_Z);
                $fatal;
            end else begin
                $display("[PASS] No X values");
                $display("OUT_X = %h", OUT_X);
                $display("OUT_Y = %h", OUT_Y);
                $display("OUT_Z = %h", OUT_Z);
            end
        end
    endtask


    task automatic check_expected;
        input logic [255:0] exp_x;
        input logic [255:0] exp_y;
        input logic [255:0] exp_z;
        begin
            check_no_x();

            if ((OUT_X !== exp_x) || (OUT_Y !== exp_y) || (OUT_Z !== exp_z)) begin
                $display("[FAIL] Output mismatch");
                $display("OUT_X = %h", OUT_X);
                $display("EXP_X = %h", exp_x);
                $display("OUT_Y = %h", OUT_Y);
                $display("EXP_Y = %h", exp_y);
                $display("OUT_Z = %h", OUT_Z);
                $display("EXP_Z = %h", exp_z);
                $fatal;
            end else begin
                $display("[PASS] Output matches expected Python reference");
            end
        end
    endtask


    initial begin
        $display("========================================");
        $display("=== tb_pippenger_window_4L start ===");
        $display("========================================");

        // ------------------------------------------------------------
        // Mini Pippenger window test:
        //
        // Inputs:
        //   P0 = G   -> bucket 1
        //   P1 = 2G  -> bucket 2
        //   P2 = 3G  -> bucket 3
        //   P3 = G   -> bucket 1
        //
        // bucket_build result:
        //   B1 = G + G = 2G
        //   B2 = 2G
        //   B3 = 3G
        //
        // reduce_buckets result:
        //   result = 1*B1 + 2*B2 + 3*B3
        //
        // Expected generated by:
        //   tests/python/gen_expected_window4.py
        // ------------------------------------------------------------

        $display("");
        $display("[TEST 1] full mini window: bucket_build_4L -> reduce_buckets_4L");

        // P0 = G affine Montgomery, bucket 1
        P0_X   = 256'h9981e643e9089f48979f48c033fd129c231e295329bc66dbd7362e5a487e2097;
        P0_Y   = 256'hcf3f851fd4a582d670b6b59aac19c1368dfc5d5d1f1dc64db15ea6d2d3dbabe2;
        P0_bid = 2'd1;

        // P1 = 2G affine Montgomery, bucket 2
        P1_X   = 256'hf918623ccba0ee23ce0b62e1e014040471354afc88b285a04e0640c981048d2c;
        P1_Y   = 256'h3c7f7712157b93134b3a0f64bda2cc6584fd25167dc75ce17d12d622ffaccfbf;
        P1_bid = 2'd2;

        // P2 = 3G affine Montgomery, bucket 3
        P2_X   = 256'h9497730fcdf4c0ad5940d07385985972066ceafb22eb7bc42379d4bbd5fea781;
        P2_Y   = 256'h3ec28dcd9215ec76cc6048bd84885650ac4964cdc5a1f91faf18b0b0613f55a9;
        P2_bid = 2'd3;

        // P3 = G affine Montgomery, bucket 1
        P3_X   = 256'h9981e643e9089f48979f48c033fd129c231e295329bc66dbd7362e5a487e2097;
        P3_Y   = 256'hcf3f851fd4a582d670b6b59aac19c1368dfc5d5d1f1dc64db15ea6d2d3dbabe2;
        P3_bid = 2'd1;

        #10;

        check_expected(
            256'h095bc488048e05a5732c475c3a609efcc38ec30f0b30a04e778684e3dd149772,
            256'ha95c53d653dee15be8482ad23b040a470b14dc6069a4204c751d6c1c6d8fdc7d,
            256'h93f59ac795686cc45912cc7f9918de3f914dbda84ad1331e5c2fd8da0ebf9998
        );

        $display("");
        $display("========================================");
        $display("=== tb_pippenger_window_4L PASSED ===");
        $display("========================================");

        $finish;
    end

endmodule