`timescale 1ns/1ps

module tb_pippenger_window_mem_stream_vector;

    parameter int ADDR_W          = 8;
    parameter int DATA_W          = 256;
    parameter int DEPTH           = (1 << ADDR_W);
    parameter int SRAM_RD_LATENCY = 3;

    // ------------------------------------------------------------
    // Vector include generated by:
    //   python3 vectors/gen_window_vectors.py ...
    //
    // To change vector, edit this include line.
    // Examples:
    //   vectors/window_16_uniform_w8.svh
    //   vectors/window_16_hot1_w8.svh
    //   vectors/window_64_uniform_w8.svh
    //   vectors/window_64_hot1_w8.svh
    // ------------------------------------------------------------
    `include "vectors/window_64_hot1_w8.svh"

    // Constant Jacobian point representations
    localparam logic [255:0] ZERO =
        256'h0000000000000000000000000000000000000000000000000000000000000000;

    localparam logic [255:0] ONE_M =
        256'h00000000000000000000000000000000000000000000000000000001000003D1;

    // Testbench Driving Signals
    logic clk;
    logic rst_n;
    logic start;
    logic busy;
    logic done;

    // Streaming interface stimulus lines
    logic                in_valid;
    logic                in_ready;
    logic [ADDR_W-1:0]   in_bucket_id;
    logic [DATA_W-1:0]   in_point_x;
    logic [DATA_W-1:0]   in_point_y;
    logic                last_point;

    // Verification output lines
    logic [DATA_W-1:0] result_x;
    logic [DATA_W-1:0] result_y;
    logic [DATA_W-1:0] result_z;

    // Basic latency metrics
    int unsigned cycle_cnt;
    int unsigned start_cycle;
    int unsigned latency;

    // Performance counters per test case
    int unsigned perf_total_cycles;
    int unsigned perf_busy_cycles;
    int unsigned perf_idle_cycles;
    int unsigned perf_input_valid_cycles;
    int unsigned perf_input_accept_count;
    int unsigned perf_input_stall_cycles;
    int unsigned perf_expected_points;

    // Dynamic arrays used by existing run_case_stream task
    logic [255:0]      x_dyn [];
    logic [255:0]      y_dyn [];
    logic [ADDR_W-1:0] b_dyn [];

    // Device Under Test (DUT) Instantiation
    pippenger_window_mem_stream_top #(
        .ADDR_W          (ADDR_W),
        .DATA_W          (DATA_W),
        .DEPTH           (DEPTH),
        .SRAM_RD_LATENCY (SRAM_RD_LATENCY)
    ) dut (
        .clk          (clk),
        .rst_n        (rst_n),
        .start        (start),
        .in_valid     (in_valid),
        .in_ready     (in_ready),
        .in_bucket_id (in_bucket_id),
        .in_point_x   (in_point_x),
        .in_point_y   (in_point_y),
        .last_point   (last_point),
        .busy         (busy),
        .done         (done),
        .result_x     (result_x),
        .result_y     (result_y),
        .result_z     (result_z)
    );

    // Clock Generator (10ns Period -> 100MHz)
    initial clk = 1'b0;
    always #5 clk = ~clk;

    // Simulation absolute cycle monitor
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            cycle_cnt <= 0;
        end else begin
            cycle_cnt <= cycle_cnt + 1;
        end
    end

    // ------------------------------------------------------------
    // Copy fixed-size generated vector arrays into dynamic arrays.
    //
    // Reason:
    //   The generated .svh declares fixed unpacked arrays:
    //      vec_point_x[0:VEC_NUM_POINTS-1]
    //
    //   The existing reusable task uses dynamic array formals:
    //      input logic [255:0] x_stream[]
    //
    //   So we bridge them once before running the case.
    // ------------------------------------------------------------
    task automatic load_generated_vectors_to_dynamic_arrays();
        begin
            x_dyn = new[VEC_NUM_POINTS];
            y_dyn = new[VEC_NUM_POINTS];
            b_dyn = new[VEC_NUM_POINTS];

            for (int i = 0; i < VEC_NUM_POINTS; i++) begin
                x_dyn[i] = vec_point_x[i];
                y_dyn[i] = vec_point_y[i];
                b_dyn[i] = vec_bucket_idx[i];
            end
        end
    endtask

    // Reusable Streaming Task using dynamic array sizes
    task automatic run_case_stream(
        input string test_name,
        input logic [255:0] x_stream[],
        input logic [255:0] y_stream[],
        input logic [ADDR_W-1:0] b_stream[],
        input logic [255:0] exp_x,
        input logic [255:0] exp_y,
        input logic [255:0] exp_z
    );
        int stream_size;

        begin
            stream_size = x_stream.size();

            // Wait until the DUT is completely idle.
            // This also protects us from starting before the one-time tag init is done.
            @(posedge clk);
            wait (busy === 1'b0);
            @(negedge clk);

            // Reset performance counters for this test case
            perf_total_cycles        = 0;
            perf_busy_cycles         = 0;
            perf_idle_cycles         = 0;
            perf_input_valid_cycles  = 0;
            perf_input_accept_count  = 0;
            perf_input_stall_cycles  = 0;
            perf_expected_points     = stream_size;

            // Assert top-level start for one cycle.
            // The DUT no longer clears X/Y/Z memory per window.
            // It only increments current_gen and uses generation tags.
            start_cycle = cycle_cnt;
            start       = 1'b1;

            @(negedge clk);
            start = 1'b0;

            // Performance monitor for this window.
            fork
                begin : PERF_MONITOR
                    while (done !== 1'b1) begin
                        @(posedge clk);

                        perf_total_cycles++;

                        if (busy) begin
                            perf_busy_cycles++;
                        end else begin
                            perf_idle_cycles++;
                        end

                        if (in_valid) begin
                            perf_input_valid_cycles++;
                        end

                        if (in_valid && in_ready) begin
                            perf_input_accept_count++;
                        end

                        if (in_valid && !in_ready) begin
                            perf_input_stall_cycles++;
                        end
                    end
                end
            join_none

            // Sequentially stream out the elements inside the arrays
            for (int i = 0; i < stream_size; i++) begin
                in_point_x   = x_stream[i];
                in_point_y   = y_stream[i];
                in_bucket_id = b_stream[i];
                in_valid     = 1'b1;

                // Set last_point concurrently with the final packet
                if (i == stream_size - 1) begin
                    last_point = 1'b1;
                end else begin
                    last_point = 1'b0;
                end

                // Stall verification sequence until DUT captures packet via in_ready
                @(posedge clk);
                while (!in_ready) begin
                    @(posedge clk);
                end

                // Clear validation line for single clock isolation
                @(negedge clk);
                in_valid   = 1'b0;
                last_point = 1'b0;
            end

            // Stall thread until core triggers window completion flag
            wait (done === 1'b1);
            latency = cycle_cnt - start_cycle;

            // Verification checker block
            if (result_x !== exp_x || result_y !== exp_y || result_z !== exp_z) begin
                $display("[TB] %s FAILED", test_name);
                $display("[TB] EXPECTED X = %064h", exp_x);
                $display("[TB] GOT      X = %064h", result_x);
                $display("[TB] EXPECTED Y = %064h", exp_y);
                $display("[TB] GOT      Y = %064h", result_y);
                $display("[TB] EXPECTED Z = %064h", exp_z);
                $display("[TB] GOT      Z = %064h", result_z);
                $fatal(1, "[TB] Stream vector mismatch error.");
            end else begin
                $display("[TB] %s PASSED latency=%0d cycles", test_name, latency);

                $display("[PERF] %s expected_points        = %0d", test_name, perf_expected_points);
                $display("[PERF] %s total_cycles           = %0d", test_name, perf_total_cycles);
                $display("[PERF] %s busy_cycles            = %0d", test_name, perf_busy_cycles);
                $display("[PERF] %s idle_cycles            = %0d", test_name, perf_idle_cycles);
                $display("[PERF] %s input_valid_cycles     = %0d", test_name, perf_input_valid_cycles);
                $display("[PERF] %s input_accept_count     = %0d", test_name, perf_input_accept_count);
                $display("[PERF] %s input_stall_cycles     = %0d", test_name, perf_input_stall_cycles);

                if (perf_input_accept_count != perf_expected_points) begin
                    $display("[PERF_WARN] %s accepted point count mismatch: expected=%0d got=%0d",
                             test_name, perf_expected_points, perf_input_accept_count);
                end
            end

            @(posedge clk);
            repeat (3) @(posedge clk);
        end
    endtask

    // Stimulus Initialization
    initial begin
        // Force initial reset states
        start        = 1'b0;
        in_valid     = 1'b0;
        in_bucket_id = '0;
        in_point_x   = '0;
        in_point_y   = '0;
        last_point   = 1'b0;

        // System Cold Reset Sequence
        rst_n = 1'b0;
        repeat (5) @(posedge clk);
        rst_n = 1'b1;

        // Wait for one-time tag memory initialization after reset.
        wait (busy === 1'b0);
        repeat (2) @(posedge clk);

        $display("[TB] Starting VECTOR pippenger_window_mem_stream_top validation");
        $display("[TB] Configuration: ADDR_W=%0d DEPTH=%0d SRAM_RD_LATENCY=%0d",
                 ADDR_W, DEPTH, SRAM_RD_LATENCY);
        $display("[TB] Vector configuration: VEC_NUM_POINTS=%0d VEC_ADDR_W=%0d VEC_DEPTH=%0d",
                 VEC_NUM_POINTS, VEC_ADDR_W, VEC_DEPTH);

        if (VEC_ADDR_W != ADDR_W) begin
            $fatal(1, "[TB] Vector ADDR_W mismatch: VEC_ADDR_W=%0d TB ADDR_W=%0d",
                   VEC_ADDR_W, ADDR_W);
        end

        if (VEC_DEPTH != DEPTH) begin
            $fatal(1, "[TB] Vector DEPTH mismatch: VEC_DEPTH=%0d TB DEPTH=%0d",
                   VEC_DEPTH, DEPTH);
        end

        load_generated_vectors_to_dynamic_arrays();

        run_case_stream(
            "python_generated_vector_stream",
            x_dyn,
            y_dyn,
            b_dyn,
            VEC_EXPECTED_X,
            VEC_EXPECTED_Y,
            VEC_EXPECTED_Z
        );

        $display("[TB] Vector stream verification PASSED.");
        #20;
        $finish;
    end

    // Simple Timeout Guard Window
    initial begin
        #5000000;
        $display("[TB] ERROR: Simulation hit maximum watchdog limit timeout!");
        $finish;
    end

endmodule
